### ISSUE TITLE
controller with too much responsibility

### ISSUE THREAD

**Issue by samvloeberghs** [Buccaneer/goegefietst#47]
This controller has way too much responsibility which could be abstracted in a service or it should be split in components:

https://github.com/Buccaneer/goegefietst/blob/develop/www/app/performance/performance-personal/personal-performance.controller.js

Main reasons why:

- again testability
- code readability ( I'm scared of figuring out what the controller can do in total )

**Comment by samvloeberghs** [comment]
For example, the chart can be it's own module / component / ..

**Comment by Buccaneer** [comment]
Moved to https://github.com/goegefietst/app/issues/22
