### ISSUE TITLE
agree on styling formats

### ISSUE THREAD

**Issue by samvloeberghs** [Buccaneer/goegefietst#49]
I see that there are different code styles used, especially in formatting syntax.
Agree on some basic stuff. For example:

https://github.com/Buccaneer/goegefietst/blob/develop/www/app/geolocation/geolocation.service.js#L6
```
angular
    .module('geolocation')
    .factory('BackgroundGeolocationService', ['$q', '$rootScope', function($q, $rootScope) {}
```
Here you guys use the array syntax for instantiating the controller. This is good, but only necesary when you are doing minification. Putting the names of the services in quotes has only the goal for angular to still know which services it should pas along as dependency when you have minified:

```
a.module('geolocation')
    .factory('BackgroundGeolocationService', ['$q', '$rootScope', function(b, c) {}
```

In other places it's more about code formatting:
https://github.com/Buccaneer/goegefietst/blob/develop/www/app/tracker/tracker.controller.js

```
  angular
    .module('app.tracker')
    .controller('TrackerController', Controller);
  //dependencies
  Controller.$inject = ['$scope',
  '$http',
  '$window',
  '$state',
  'leafletData',
  'BackgroundGeolocationService',
  'Database'];

  /* @ngInject */
  function Controller($scope,
    $http,
    $window,
    $state,
    leafletData,
    BackgroundGeolocationService,
    Database) {}
```
Here $inject is used, which has the same goal as above.
And in this case you don't need the @ngInject, because that's again what that does: putting the `$inject` in code during a build step.

Second point is the difference in styling: everything on a new line here, compared to everything on the same line in the first example.

Agree on some basic rules. And best is to use a style guide from John Papa or Minko Gechev:

- http://blog.mgechev.com/2013/10/06/angularjs-style-guide/
- https://github.com/johnpapa/angular-styleguide

**Comment by Buccaneer** [comment]
Moved to: https://github.com/goegefietst/app/issues/24
